services:
  - type: web
    name: tentarte
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 1 --threads 4
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.9
      - key: HTTPS
        value: "1"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ADMIN_PASSWORD
        generateValue: true
